name: Build and deploy Node.js app to Azure Web App - personal-outlook-mcp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A9F0EB7758C24EBCB15B89479C3BC5D5 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A4368CF05CFD4A6E908B3C04EBFE36F0 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8B307E4956C8461782AA0D31BF6E1DC4 }}

      - name: Deploy
        uses: azure/webapps-deploy@v3
        with:
          app-name: personal-outlook-mcp
          slot-name: Production
          package: .